### ISSUE TITLE
No available builder could be instantiated.

### ISSUE THREAD

**Issue by cervelle** [boileaum/quittances#1]
First: super idee/boulot !

Je cherche a tester code pour mes besoins perso.
J'ai l'erreur suivante : 
RuntimeError: No available builder could be instantiated. Please make sure LaTeX is installed.

A priori ce n'est pas suffisant mais j'ai install latex via pip (je suis novice en python)
pip install latex
J'ai manque qqch ?

Merci d'avance.

PS : j'avais une autre erreur initialement et en replacant la method load par safe_load ligne 37 ca a l'air de l'avoir resolu.

**Comment by boileaum** [comment]
Le plus simple est d'instancier un notebook Jupyter en cliquant sur le badge "Launch Binder" du [README](README.md) : rien à installer, tout est en ligne !

L'environnement que lance mybinder est décrit par ce [Dockerfile](docker/Dockerfile) qui est lui-même  construit à partir de cette [image docker](../../dockerfiles/blob/master/latexfr/Dockerfile).
Pour faire une installation locale en dehors de Docker, il faut d'abord installer Latex, par exemple avec le gestionnaire de paquets du système (on peut s'inspirer du [Dockerfile](../../dockerfiles/blob/master/latexfr/Dockerfile)), puis faire un :

```
pip install -r requirements.txt
```

**Comment by cervelle** [comment]
Super merci  :D
